import * as z from "zod";

export const roomSchema = z.object({
  RoomName: z.string().min(3, "Room name must be at least 3 characters"),
  RoomOwner: z.string().min(2, "Room owner name is required"),
  ContactNumber: z
    .string()
    .min(10, "Contact number must be at least 10 digits"),
  SecondaryContactNumber: z.string().optional().nullable(),
  IsActive: z.enum(["Yes", "No", "Deleted"]),
  isDeletedRoom: z.boolean(),
  RoomAddress: z.string().min(5, "Room address is required"),
  AdvertisementStartDate: z.string().optional().nullable(),
  AdvertisementEndDate: z.string().optional().nullable(),
  RentPrice: z.string().min(1, "Rent price is required"),
  RentType: z.enum(["PG", "Room", "PG & Room"]),
  RoomType: z.enum(["Male", "Female", "Family"]),
  Description: z.string().min(10, "Description must be at least 10 characters"),
  District: z.string().min(1, "District is required"),
  State: z.string().min(1, "State is required"),
  PinCode: z.string().regex(/^\d{6}$/, "Pincode must be exactly 6 digits"),
  images: z.any().optional(),
  VideoLink: z.string().url("Invalid video URL").optional().or(z.literal("")),
  VideoLinkId: z.string().nullable().optional(),
  NoOfBed: z.string().min(1, "Number of beds is required"),
  NoOfShare: z.string().min(1, "Sharing details are required"),
  NoOfWashroom: z.string().min(1, "Number of washrooms is required"),
  IsAc: z.boolean(),
  IsTv: z.boolean(),
  IsAquaguard: z.boolean(),
  IsWifi: z.boolean(),
  IsParking: z.boolean(),
  IsElevator: z.boolean(),
  IsGeyser: z.boolean(),
  IsPowerBackup: z.boolean(),
  IsCCTV: z.boolean(),
  IsKitchen: z.boolean(),
  IsRefrigerator: z.boolean(),
  IsFoodFacilities: z.boolean(),
  IsBedProvided: z.boolean(),
  IsSecurityGuard: z.boolean(),
});

export type RoomFormValues = z.infer<typeof roomSchema>;

export const roomDefaultValues: RoomFormValues = {
  RoomName: "",
  RoomOwner: "",
  ContactNumber: "",
  SecondaryContactNumber: "",
  IsActive: "Yes",
  isDeletedRoom: false,
  RoomAddress: "",
  AdvertisementStartDate: "",
  AdvertisementEndDate: "",
  RentPrice: "",
  RentType: "PG",
  RoomType: "Male",
  Description: "",
  District: "",
  State: "",
  PinCode: "",
  images: null,
  VideoLink: "",
  VideoLinkId: "",
  NoOfBed: "",
  NoOfShare: "",
  NoOfWashroom: "",
  IsAc: false,
  IsTv: false,
  IsAquaguard: false,
  IsWifi: false,
  IsParking: false,
  IsElevator: false,
  IsGeyser: false,
  IsPowerBackup: false,
  IsCCTV: false,
  IsKitchen: false,
  IsRefrigerator: false,
  IsFoodFacilities: false,
  IsBedProvided: false,
  IsSecurityGuard: false,
};
